### PR TITLE
Added implementation of resest button to reset QR scanner

### PR DESCRIPTION
**Pull request by sunjogthind**

### CODE REVIEW

**Comment by jsh3lly** [comment]
I tried testing your code and for me, the scanner seems to get unresponsive after scanning a code. This seems to be an issue on `main` as well. I don't know if your intention behind making the background gray was to "hide" the QR Code or not, but the issue still persists. Maybe it worked for your emulator.

Others, please test and let me know if after scanning a QR code, does the QR code scanner become unresponsive?

**Comment by khanheric2003** [comment]
Yes, it is its function inside the library, you could double tap it to stop the frame freeze, due to its inconvenience, that's why we have to implement the reset button to make it more clear about the frame freeze feature.

**Comment by jsh3lly** [comment]
I see @khanheric2003, so the reset button is not done correctly, right?

**Comment by khanheric2003** [comment]
I just checked for this PR, the reset button is not implemented correctly and the big error would be after scanning a code, it is not supposed to return a gray screen and wait for a reset button to show the frozen frame, 
What it does, is it should just leave the frame freeze when the code was captured
--> then  the reset button would stop the frozen frame for the user to continue capturing another qr code

**Pull request closed without merging**
